# Color theme
include PaulMillr.conf

# Font
font_family      RecMonoLinear Nerd Font Mono
bold_font        RecMonoLinear Nerd Font Mono Bold
italic_font      RecMonoLinear Nerd Font Bold Italic
bold_italic_font RecMonoLinear Nerd Font Italic

# Tengwar (CSUR)
symbol_map U+E000-U+E07F Fairfax HD 

# BELL handling 
bell_path ~/.local/share/sounds/hl2/mono/flashlight1.ogg
visual_bell_duration 0.25
visual_bell_color #ffffff
