#!/usr/bin/env bash

set -e

CONFIG_LOCATION=$(pwd)

# install keyd
# (among other things, makes Caps Lock the ESC key.)
if ! is_service_installed "keyd.service"; then
  echo "keyd is not installed";
  cd deps/keyd.git 
  git reset --hard HEAD
  make && sudo make install
  sudo systemctl enable --now keyd
fi

cd $CONFIG_LOCATION
# update keyd config and restart
echo "updating keyd config"
sudo cp config/keyd/keyd.conf /etc/keyd/default.conf
sudo systemctl restart keyd
