require('montserrat.packages')
require('montserrat.preferences')
require('montserrat.completions')
require('montserrat.keys')
require('montserrat.telescope')
require('montserrat.treesitter')
require('montserrat.lsp')
